#!/bin/bash

set -e

. ~/.bashrc

: ${COUCHDB_THREADS:=25}

# options: debug info warning error none
: ${COUCHDB_LOG_LEVEL:=info}

: ${COUCHDB_DATA_PATH:=/opt/couchdb/data}
: ${COUCHDB_BIND_ADDR:=0.0.0.0}

: ${COUCHDB_SHARDS:=4}
: ${COUCHDB_READ_QUORUM:=1}
: ${COUCHDB_WRITE_QUORUM:=1}
: ${COUCHDB_REPLICAS:=3}


if [ "$MOUNT_PERSISTENT_VOLUME" = true ]; then
    VOLUME_MOUNT_PATH="/mnt/couchdb-data/$(hostname)"

    echo -e "Using Persistent Volume ...
    host: $(hostname)
    volume-mount-path: $VOLUME_MOUNT_PATH
    couchdb-data-path: $COUCHDB_DATA_PATH
    "
    mkdir -p $VOLUME_MOUNT_PATH
    ln -sf $VOLUME_MOUNT_PATH $COUCHDB_DATA_PATH
else
    mkdir -p $COUCHDB_DATA_PATH
fi


echo "Writing vm.args file ..."
tee ~/etc/vm.args <<EOF
-name couchdb@$(hostname -f)
+K true
+A $COUCHDB_THREADS
-kernel error_logger silent inet_dist_listen_min 11500 inet_dist_listen_max 11999
-sasl sasl_error_logger false
+Bd -noinput
EOF


echo "Rewriting local.ini file ..."
tee ~/etc/local.ini <<EOF
[couchdb]
database_dir = $COUCHDB_DATA_PATH
view_index_dir = $COUCHDB_DATA_PATH

[chttpd]
require_valid_user = false
port = 5984
bind_address = $COUCHDB_BIND_ADDR

[httpd]
require_valid_user = false
port = 5986
bind_address = $COUCHDB_BIND_ADDR

[cluster]
q=$COUCHDB_SHARDS
n=$COUCHDB_REPLICAS
r=$COUCHDB_READ_QUORUM
w=$COUCHDB_WRITE_QUORUM

[log]
level = $COUCHDB_LOG_LEVEL
EOF


echo "Reading erlang cookie ..."
if [ -f '/etc/secrets/erlang/cookie' ]; then
    echo "Cookie secret mounted ..."
    ERLANG_COOKIE=$(cat /etc/secrets/erlang/cookie)
else
    echo "*** No Erlang Cookie Mounted! ***"
    ERLANG_COOKIE=insecure-cookie
fi
echo "$ERLANG_COOKIE" > ~/.erlang.cookie


echo "Ensuring correct permissions ..."
chown -R couchdb:couchdb ~
chmod -R 0755 ~/data
chmod 0600 ~/.erlang.cookie 


cd ~
    echo "Starting couchdb ..."
    cat >&2 <<-'EOF'

************************************************************
WARNING: if running as a single node, remember to 
         initialize the system dbs using:
         
curl -X PUT http://localhost:5984/_users
curl -X PUT http://localhost:5984/_replicator
curl -X PUT http://127.0.0.1:5984/_global_changes

************************************************************

EOF
    export ERL_CRASH_DUMP=$(date +%s)_couchdb_crash.dump
    
    exec gosu couchdb couchdb 2>&1
