#!/bin/bash -l

set -e

app=couchdb
user=$app

if [ -f /etc/default/$app ]
then
    . /etc/default/$app
fi

: ${ERLANG_THREADS:=25}

# options: debug info warning error none
: ${COUCHDB_LOG_LEVEL:=info}

: ${COUCHDB_DATA_PATH:=/data/$app}
: ${COUCHDB_BIND_ADDR:=0.0.0.0}

: ${COUCHDB_REQUIRE_VALID_USER:=false}
: ${COUCHDB_ADMIN_USER:=admin}
: ${COUCHDB_ADMIN_PASS:=secret}

: ${COUCHDB_SHARDS:=4}
: ${COUCHDB_READ_QUORUM:=1}
: ${COUCHDB_WRITE_QUORUM:=1}
: ${COUCHDB_REPLICAS:=3}

function log 
{
    local msg="$1"
    echo -e "\E[36m[*]\E[0m ${msg}" 
}

if [[ $KUBERNETES_HOSTNAME_FIX = true ]]
then
    eval $(fix-kube-hostname enable)
fi

if [[ $PERSISTENT_STORAGE_ENABLED = true ]]
then 
    persistent-volume-util link $app
fi


log "Writing erlang cookie ..." 
write-erlang-cookie


log "Writing vm.args file ..."
tee ~/etc/vm.args <<EOF
# Turn off the sasl error logger
-sasl sasl_error_logger false

# Use the following erlang long hostname
-name couchdb@$(env hostname -f)

# Use kernel poll functionality if supported by emulator
+K true

# Start a pool of asynchronous IO threads
+A $ERLANG_THREADS

# Turn off the kernel error_logger
-kernel error_logger silent 

# Set erlang distribution to use 11500-11999 ports instead of random
# predictibility has value here
-kernel inet_dist_listen_min 11500 inet_dist_listen_max 11999

# Comment this line out if you want the Erlang shell
+Bd -noinput
EOF


# admins section commented for now, broken implementation
log "Rewriting local.ini file ..."
tee ~/etc/local.ini <<EOF
[couchdb]
database_dir = $COUCHDB_DATA_PATH
view_index_dir = $COUCHDB_DATA_PATH

[chttpd]
require_valid_user = $COUCHDB_REQUIRE_VALID_USER
port = 5984
bind_address = $COUCHDB_BIND_ADDR

[httpd]
require_valid_user = $COUCHDB_REQUIRE_VALID_USER
port = 5986
bind_address = $COUCHDB_BIND_ADDR

[cluster]
q=$COUCHDB_SHARDS
n=$COUCHDB_REPLICAS
r=$COUCHDB_READ_QUORUM
w=$COUCHDB_WRITE_QUORUM

[log]
level = ${COUCHDB_LOG_LEVEL,,}

;[admins]
;$COUCHDB_ADMIN_USER = $COUCHDB_ADMIN_PASS
EOF


log "Ensuring correct permissions ..."
chown -R $user:$user ~


cd ~
    log "Starting $app ..."
    export ERL_CRASH_DUMP=$(date +%s)_${app}_crash.dump
    
    # this script handles annoying post-init tasks automatically,
    # and deletes ~/.init-node
    [[ -f ~/.init-node ]] && ~/init-node.sh > /dev/null 2>&1 &

    exec gosu $user couchdb 2>&1
